# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[(b'P', b'Post'), (b'J', b'Job Post'), (b'AMA', b'Ask Me Anything')], default=b'P', max_length=30),
        ),
    ]
