# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-09 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190328_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(blank=True, default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('P', 'Post'), ('J', 'Job Post'), ('AMA', 'Ask Me Anything')], default='P', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
